[2024-06-30T08:00:51.716+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-30T08:00:51.739+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwindDWH.data_delivery manual__2024-06-30T08:00:48.081126+00:00 [queued]>
[2024-06-30T08:00:51.750+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwindDWH.data_delivery manual__2024-06-30T08:00:48.081126+00:00 [queued]>
[2024-06-30T08:00:51.750+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-30T08:00:51.767+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-06-30 08:00:48.081126+00:00
[2024-06-30T08:00:51.777+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=69) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-30T08:00:51.778+0000] {standard_task_runner.py:63} INFO - Started process 71 to run task
[2024-06-30T08:00:51.779+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'northwindDWH', 'data_delivery', 'manual__2024-06-30T08:00:48.081126+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/northwindDWH.py', '--cfg-path', '/tmp/tmpf23popa6']
[2024-06-30T08:00:51.781+0000] {standard_task_runner.py:91} INFO - Job 66: Subtask data_delivery
[2024-06-30T08:00:51.793+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-06-30T08:00:51.826+0000] {task_command.py:426} INFO - Running <TaskInstance: northwindDWH.data_delivery manual__2024-06-30T08:00:48.081126+00:00 [running]> on host 3abb3aef8f21
[2024-06-30T08:00:51.935+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='northwindDWH' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-06-30T08:00:48.081126+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-30T08:00:48.081126+00:00'
[2024-06-30T08:00:51.936+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-30T08:00:51.951+0000] {northwindDWH.py:49} INFO - Data delivery started
[2024-06-30T08:00:51.952+0000] {Load_data.py:85} INFO - loading dimEmployee to db ...
[2024-06-30T08:00:51.952+0000] {Transform_data.py:48} INFO - start Extracting dim employee
[2024-06-30T08:00:51.956+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T08:00:51.959+0000] {Transform_data.py:57} INFO - Extract dim employees done
[2024-06-30T08:00:51.960+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T08:00:51.963+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T08:00:51.968+0000] {Load_data.py:103} INFO - SCD type 2 on dimemployee started
[2024-06-30T08:00:51.994+0000] {Tables_creations.py:27} INFO - Loading data into table dim_employee...
[2024-06-30T08:00:51.998+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T08:00:52.004+0000] {Tables_creations.py:41} INFO - Data loaded successfully into table dim_employee With 9 Row
[2024-06-30T08:00:52.005+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T08:00:52.006+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T08:00:52.006+0000] {Load_data.py:158} INFO - loading dimproduct to db ...
[2024-06-30T08:00:52.007+0000] {Transform_data.py:25} INFO - start Extracting dim product
[2024-06-30T08:00:52.010+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T08:00:52.014+0000] {Transform_data.py:39} INFO - Extract dim products done
[2024-06-30T08:00:52.014+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T08:00:52.018+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T08:00:52.021+0000] {Load_data.py:172} INFO - SCD type 1 on dimproduct started
[2024-06-30T08:00:52.023+0000] {Load_data.py:203} INFO - Error while loading dimProducts: 'product_id'
[2024-06-30T08:00:52.023+0000] {Load_data.py:12} INFO - loading dimCustomers to db ...
[2024-06-30T08:00:52.024+0000] {Transform_data.py:7} INFO - start Extracting dim customers
[2024-06-30T08:00:52.027+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T08:00:52.030+0000] {Transform_data.py:16} INFO - Extract dim customer done
[2024-06-30T08:00:52.030+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T08:00:52.034+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T08:00:52.037+0000] {Load_data.py:30} INFO - SCD type 2 on dimcustomer started
[2024-06-30T08:00:52.099+0000] {Tables_creations.py:27} INFO - Loading data into table dim_customers...
[2024-06-30T08:00:52.103+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T08:00:52.116+0000] {Tables_creations.py:41} INFO - Data loaded successfully into table dim_customers With 29 Row
[2024-06-30T08:00:52.117+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T08:00:52.117+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T08:00:52.118+0000] {Load_data.py:207} INFO - Loading factsales to db ...
[2024-06-30T08:00:52.118+0000] {Transform_data.py:67} INFO - start Extracting fact sales
[2024-06-30T08:00:52.122+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T08:00:52.125+0000] {Transform_data.py:80} INFO - Extract fact sales done
[2024-06-30T08:00:52.126+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T08:00:52.128+0000] {Tables_creations.py:27} INFO - Loading data into table fact_sales...
[2024-06-30T08:00:52.131+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T08:00:52.138+0000] {Load_data.py:218} INFO - Error while loading Fact_Sales: invalid input syntax for type timestamp: "NaT"
LINE 1: ... (41, 43, 1, 7, '2006-03-24T00:00:00'::timestamp, 'NaT'::tim...
                                                             ^

[2024-06-30T08:00:52.139+0000] {northwindDWH.py:54} INFO - Data delivery done
[2024-06-30T08:00:52.139+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-30T08:00:52.140+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-30T08:00:52.148+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=northwindDWH, task_id=data_delivery, run_id=manual__2024-06-30T08:00:48.081126+00:00, execution_date=20240630T080048, start_date=20240630T080051, end_date=20240630T080052
[2024-06-30T08:00:52.192+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-30T08:00:52.209+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-30T08:00:52.211+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
