[2024-06-30T08:41:28.167+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-30T08:41:28.191+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwindDWH.data_delivery manual__2024-06-30T08:38:24.128669+00:00 [queued]>
[2024-06-30T08:41:28.199+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwindDWH.data_delivery manual__2024-06-30T08:38:24.128669+00:00 [queued]>
[2024-06-30T08:41:28.199+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-30T08:41:28.211+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-06-30 08:38:24.128669+00:00
[2024-06-30T08:41:28.218+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=132) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-30T08:41:28.220+0000] {standard_task_runner.py:63} INFO - Started process 134 to run task
[2024-06-30T08:41:28.220+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'northwindDWH', 'data_delivery', 'manual__2024-06-30T08:38:24.128669+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/northwindDWH.py', '--cfg-path', '/tmp/tmpomwcidgb']
[2024-06-30T08:41:28.222+0000] {standard_task_runner.py:91} INFO - Job 87: Subtask data_delivery
[2024-06-30T08:41:28.232+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-06-30T08:41:28.263+0000] {task_command.py:426} INFO - Running <TaskInstance: northwindDWH.data_delivery manual__2024-06-30T08:38:24.128669+00:00 [running]> on host 3abb3aef8f21
[2024-06-30T08:41:28.351+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='northwindDWH' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-06-30T08:38:24.128669+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-30T08:38:24.128669+00:00'
[2024-06-30T08:41:28.352+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-30T08:41:28.365+0000] {northwindDWH.py:49} INFO - Data delivery started
[2024-06-30T08:41:28.366+0000] {Load_data.py:85} INFO - loading dimEmployee to db ...
[2024-06-30T08:41:28.366+0000] {Transform_data.py:51} INFO - start Extracting dim employee
[2024-06-30T08:41:28.369+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T08:41:28.373+0000] {Transform_data.py:60} INFO - Extract dim employees done
[2024-06-30T08:41:28.374+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T08:41:28.379+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T08:41:28.381+0000] {Load_data.py:103} INFO - SCD type 2 on dimemployee started
[2024-06-30T08:41:28.387+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T08:41:28.388+0000] {Load_data.py:159} INFO - Loading dimproduct to db...
[2024-06-30T08:41:28.388+0000] {Transform_data.py:27} INFO - Start Extracting dim product
[2024-06-30T08:41:28.392+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T08:41:28.395+0000] {Transform_data.py:41} INFO - Extract dim products done
[2024-06-30T08:41:28.395+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T08:41:28.399+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T08:41:28.402+0000] {Load_data.py:171} INFO - SCD type 1 on dimproduct started
[2024-06-30T08:41:28.402+0000] {Load_data.py:210} ERROR - Error while loading dimProducts: 'Product_id'
[2024-06-30T08:41:28.403+0000] {Load_data.py:12} INFO - loading dimCustomers to db ...
[2024-06-30T08:41:28.403+0000] {Transform_data.py:7} INFO - start Extracting dim customers
[2024-06-30T08:41:28.407+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T08:41:28.409+0000] {Transform_data.py:16} INFO - Extract dim customer done
[2024-06-30T08:41:28.409+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T08:41:28.413+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T08:41:28.416+0000] {Load_data.py:30} INFO - SCD type 2 on dimcustomer started
[2024-06-30T08:41:28.430+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T08:41:28.430+0000] {Load_data.py:216} INFO - Loading factsales to db ...
[2024-06-30T08:41:28.431+0000] {Transform_data.py:70} INFO - start Extracting fact sales
[2024-06-30T08:41:28.433+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T08:41:28.436+0000] {Transform_data.py:81} INFO - Extract fact sales done
[2024-06-30T08:41:28.437+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T08:41:28.441+0000] {Tables_creations.py:27} INFO - Loading data into table fact_sales...
[2024-06-30T08:41:28.444+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T08:41:28.460+0000] {Tables_creations.py:41} INFO - Data loaded successfully into table fact_sales With 58 Row
[2024-06-30T08:41:28.460+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T08:41:28.461+0000] {Load_data.py:224} INFO - Fact_Sales loaded successfully
[2024-06-30T08:41:28.461+0000] {northwindDWH.py:54} INFO - Data delivery done
[2024-06-30T08:41:28.461+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-30T08:41:28.462+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-30T08:41:28.470+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=northwindDWH, task_id=data_delivery, run_id=manual__2024-06-30T08:38:24.128669+00:00, execution_date=20240630T083824, start_date=20240630T084128, end_date=20240630T084128
[2024-06-30T08:41:28.514+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-30T08:41:28.530+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-30T08:41:28.532+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
