[2024-06-30T08:49:35.771+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-30T08:49:35.793+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwindDWH.data_delivery manual__2024-06-30T08:49:32.176040+00:00 [queued]>
[2024-06-30T08:49:35.800+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwindDWH.data_delivery manual__2024-06-30T08:49:32.176040+00:00 [queued]>
[2024-06-30T08:49:35.801+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-30T08:49:35.813+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-06-30 08:49:32.176040+00:00
[2024-06-30T08:49:35.823+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=150) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-30T08:49:35.824+0000] {standard_task_runner.py:63} INFO - Started process 152 to run task
[2024-06-30T08:49:35.824+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'northwindDWH', 'data_delivery', 'manual__2024-06-30T08:49:32.176040+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/northwindDWH.py', '--cfg-path', '/tmp/tmp059743n5']
[2024-06-30T08:49:35.826+0000] {standard_task_runner.py:91} INFO - Job 93: Subtask data_delivery
[2024-06-30T08:49:35.837+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-06-30T08:49:35.868+0000] {task_command.py:426} INFO - Running <TaskInstance: northwindDWH.data_delivery manual__2024-06-30T08:49:32.176040+00:00 [running]> on host 3abb3aef8f21
[2024-06-30T08:49:35.958+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='northwindDWH' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-06-30T08:49:32.176040+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-30T08:49:32.176040+00:00'
[2024-06-30T08:49:35.959+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-30T08:49:35.971+0000] {northwindDWH.py:49} INFO - Data delivery started
[2024-06-30T08:49:35.971+0000] {Load_data.py:85} INFO - loading dimEmployee to db ...
[2024-06-30T08:49:35.971+0000] {Transform_data.py:51} INFO - start Extracting dim employee
[2024-06-30T08:49:35.974+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T08:49:35.978+0000] {Transform_data.py:60} INFO - Extract dim employees done
[2024-06-30T08:49:35.979+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T08:49:35.982+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T08:49:35.984+0000] {Load_data.py:103} INFO - SCD type 2 on dimemployee started
[2024-06-30T08:49:35.991+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T08:49:35.991+0000] {Load_data.py:159} INFO - Loading dimproduct to db...
[2024-06-30T08:49:35.992+0000] {Transform_data.py:27} INFO - Start Extracting dim product
[2024-06-30T08:49:35.995+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T08:49:35.997+0000] {Transform_data.py:41} INFO - Extract dim products done
[2024-06-30T08:49:35.997+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T08:49:36.001+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T08:49:36.005+0000] {Load_data.py:173} INFO - SCD type 1 on dimproduct started
[2024-06-30T08:49:36.024+0000] {Load_data.py:212} ERROR - Error while loading dimProducts: Cannot convert non-finite values (NA or inf) to integer
[2024-06-30T08:49:36.025+0000] {Load_data.py:12} INFO - loading dimCustomers to db ...
[2024-06-30T08:49:36.025+0000] {Transform_data.py:7} INFO - start Extracting dim customers
[2024-06-30T08:49:36.028+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T08:49:36.030+0000] {Transform_data.py:16} INFO - Extract dim customer done
[2024-06-30T08:49:36.030+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T08:49:36.033+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T08:49:36.036+0000] {Load_data.py:30} INFO - SCD type 2 on dimcustomer started
[2024-06-30T08:49:36.052+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T08:49:36.053+0000] {Load_data.py:217} INFO - Loading factsales to db ...
[2024-06-30T08:49:36.053+0000] {Transform_data.py:70} INFO - start Extracting fact sales
[2024-06-30T08:49:36.057+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T08:49:36.060+0000] {Transform_data.py:81} INFO - Extract fact sales done
[2024-06-30T08:49:36.061+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T08:49:36.063+0000] {Tables_creations.py:27} INFO - Loading data into table fact_sales...
[2024-06-30T08:49:36.066+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-30T08:49:36.082+0000] {Tables_creations.py:41} INFO - Data loaded successfully into table fact_sales With 58 Row
[2024-06-30T08:49:36.082+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-30T08:49:36.082+0000] {Load_data.py:225} INFO - Fact_Sales loaded successfully
[2024-06-30T08:49:36.082+0000] {northwindDWH.py:54} INFO - Data delivery done
[2024-06-30T08:49:36.083+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-30T08:49:36.083+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-30T08:49:36.093+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=northwindDWH, task_id=data_delivery, run_id=manual__2024-06-30T08:49:32.176040+00:00, execution_date=20240630T084932, start_date=20240630T084935, end_date=20240630T084936
[2024-06-30T08:49:36.118+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-30T08:49:36.134+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-30T08:49:36.135+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
